apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  artifacts:
  - image: braianmg/ticketing-auth
    context: auth
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: braianmg/ticketing-client
    context: client
    sync:
      manual:
      - src: "**/*.js"
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: braianmg/ticketing-tickets
    context: tickets
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: braianmg/ticketing-orders
    context: orders
    sync:
      manual:
      - src: "src/**/*.ts"
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: braianmg/ticketing-expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: braianmg/ticketing-payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  local:
    push: false
